#!/usr/bin/env node
/**
 * update.js — regenerates blog-index.json and photos-data.json
 *
 * Usage:
 *   node scripts/update.js            # update both blog and photos
 *   node scripts/update.js --blog     # blog only
 *   node scripts/update.js --photos   # photos only
 *
 * Cloudinary credentials (required for --photos):
 *   Set as environment variables before running, or create a .env file:
 *     CLOUDINARY_CLOUD_NAME=your_cloud_name
 *     CLOUDINARY_API_KEY=your_api_key
 *     CLOUDINARY_API_SECRET=your_api_secret
 */

const fs      = require('fs');
const path    = require('path');
const matter  = require('gray-matter');
const { marked }       = require('marked');
const sanitizeHtml     = require('sanitize-html');

marked.setOptions({ mangle: false, headerIds: false });

const ROOT = path.join(__dirname, '..');
const SITE_URL = 'https://devrashie.space';
const SITE_NAME = 'Devakh Rashie';
// First line of every page written by writePostPage(); used to find stale pages to remove.
const GENERATED_MARKER = '<!-- generated by scripts/update.js — edit the .md, not this file -->';

// ── Load .env if present ──────────────────────────────────────────────────────
const envPath = path.join(ROOT, '.env');
if (fs.existsSync(envPath)) {
  fs.readFileSync(envPath, 'utf8').split('\n').forEach(line => {
    const m = line.match(/^\s*([^#=\s]+)\s*=\s*(.*)\s*$/);
    if (m) process.env[m[1]] = m[2].replace(/^['"]|['"]$/g, '');
  });
}

// ── Helpers ───────────────────────────────────────────────────────────────────
function slugify(str) {
  return str.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
}

function formatDate(d) {
  try {
    const dt = new Date(d);
    if (isNaN(dt)) return '';
    // Front-matter dates parse as UTC midnight; format in UTC so they don't shift a day.
    return dt.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', timeZone: 'UTC' });
  } catch { return ''; }
}

function escapeHtml(s) {
  return String(s || '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
}

function renderMarkdown(mdContent) {
  const html = marked.parse(mdContent || '');
  return sanitizeHtml(html, {
    allowedTags: sanitizeHtml.defaults.allowedTags.concat(['img', 'h1', 'h2', 'h3']),
    allowedAttributes: {
      ...sanitizeHtml.defaults.allowedAttributes,
      img: ['src', 'alt', 'title', 'width', 'height'],
    },
  });
}

// ── Post pages ────────────────────────────────────────────────────────────────
// Each post gets a standalone page at blog/<slug>.html, served by GitHub Pages
// at /blog/<slug>, so it can be linked to directly.
function postPageHtml(post) {
  const url   = `${SITE_URL}${post.url}`;
  const title = escapeHtml(post.title);
  const desc  = escapeHtml(post.excerpt);
  return `${GENERATED_MARKER}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title} — ${SITE_NAME}</title>
<meta name="description" content="${desc}">
<link rel="canonical" href="${url}">
<link rel="icon" type="image/x-icon" href="/favicon.ico">
<meta property="og:title" content="${title}">
<meta property="og:description" content="${desc}">
<meta property="og:type" content="article">
<meta property="og:url" content="${url}">
<meta property="og:site_name" content="${SITE_NAME}">
<meta property="article:published_time" content="${post.date}">
<meta name="twitter:card" content="summary">
<style>
  :root {
    --bg:    #ffffff;
    --fg:    #000000;
    --muted: #666666;
    --rule:  #e0e0e0;
  }

  @media (prefers-color-scheme: dark) {
    :root {
      --bg:    #0d0d0d;
      --fg:    #ededed;
      --muted: #8c8c8c;
      --rule:  #262626;
    }
  }

  * { box-sizing: border-box; }

  html { -webkit-text-size-adjust: 100%; }

  body {
    margin: 0;
    background: var(--bg);
    color: var(--fg);
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Inter, Helvetica, Arial, sans-serif;
    font-size: 16px;
    line-height: 1.7;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }

  .page {
    max-width: 40rem;
    margin: 0 auto;
    padding: 5rem 1.5rem 6rem;
  }

  a {
    color: inherit;
    text-decoration: underline;
    text-decoration-color: var(--muted);
    text-underline-offset: 2px;
    text-decoration-thickness: 1px;
    transition: text-decoration-color .12s ease;
  }
  a:hover { text-decoration-color: var(--fg); }
  a:focus-visible { outline: 1px solid var(--fg); outline-offset: 3px; }

  .back { margin: 0 0 2.75rem; color: var(--muted); }

  h1 {
    font-size: 1.05rem;
    font-weight: 600;
    letter-spacing: -0.01em;
    margin: 0;
  }

  .post-date { color: var(--muted); margin: 0 0 1.75rem; }

  /* the page heading already shows the title */
  .post-body > h1:first-child { display: none; }
  .post-body h1 { font-size: 1.05rem; margin: 1.75rem 0 .5rem; }
  .post-body h2 {
    font-size: .95rem;
    font-weight: 600;
    margin: 1.75rem 0 .5rem;
  }
  .post-body h3 { font-size: .9rem; font-weight: 600; margin: 1.25rem 0 .4rem; }
  .post-body p { margin: 0 0 .9rem; }
  .post-body ul, .post-body ol { padding-left: 1.25rem; margin: 0 0 .9rem; }
  .post-body li { margin-bottom: .25rem; }
  .post-body code {
    font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    font-size: .875em;
    background: var(--rule);
    padding: .1em .35em;
    border-radius: 2px;
  }
  .post-body pre {
    background: var(--rule);
    padding: .85rem 1rem;
    overflow-x: auto;
    margin: 0 0 .9rem;
  }
  .post-body pre code { background: none; padding: 0; }
  .post-body blockquote {
    margin: 0 0 .9rem;
    padding-left: .9rem;
    border-left: 1px solid var(--rule);
    color: var(--muted);
  }
  .post-body img { max-width: 100%; height: auto; }
  .post-body hr { border: 0; border-top: 1px solid var(--rule); margin: 1.75rem 0; }

  @media (max-width: 560px) {
    .page { padding: 3rem 1.25rem 4rem; }
  }

  @media (prefers-reduced-motion: reduce) {
    * { transition: none !important; }
  }
</style>
</head>
<body>
<main class="page">
  <p class="back"><a href="/">← ${SITE_NAME}</a></p>
  <article>
    <h1>${title}</h1>
    <p class="post-date"><time datetime="${post.date}">${escapeHtml(post.dateFormatted)}</time></p>
    <div class="post-body">
${post.html}
    </div>
  </article>
</main>
</body>
</html>
`;
}

function writePostPages(blogDir, posts) {
  const slugs = new Set(posts.map(p => p.slug));

  // Remove pages for posts that were deleted or renamed.
  fs.readdirSync(blogDir)
    .filter(f => /\.html$/i.test(f) && !slugs.has(f.replace(/\.html$/i, '')))
    .forEach(f => {
      const fpath = path.join(blogDir, f);
      if (fs.readFileSync(fpath, 'utf8').startsWith(GENERATED_MARKER)) {
        fs.unlinkSync(fpath);
        console.log(`  removed stale blog/${f}`);
      }
    });

  posts.forEach(post => {
    fs.writeFileSync(path.join(blogDir, `${post.slug}.html`), postPageHtml(post));
  });
}

// ── Blog ──────────────────────────────────────────────────────────────────────
async function updateBlog() {
  const blogDir   = path.join(ROOT, 'blog');
  const indexPath = path.join(ROOT, 'blog-index.json');

  if (!fs.existsSync(blogDir)) {
    console.log('No blog/ directory found — skipping blog update.');
    return;
  }

  const files = fs.readdirSync(blogDir).filter(f => /\.md$/i.test(f));
  if (!files.length) {
    console.log('No .md files in blog/ — writing empty index.');
    fs.writeFileSync(indexPath, JSON.stringify({ posts: [] }, null, 2));
    writePostPages(blogDir, []);
    return;
  }

  const posts = files.map(fname => {
    const fpath   = path.join(blogDir, fname);
    const raw     = fs.readFileSync(fpath, 'utf8');
    const fm      = matter(raw);
    const title   = fm.data.title || fname.replace(/\.md$/i, '').replace(/-/g, ' ');
    const date    = fm.data.date
      ? new Date(fm.data.date).toISOString()
      : fs.statSync(fpath).mtime.toISOString();
    const slug    = slugify(String(fm.data.slug || title));
    const excerpt = fm.data.excerpt
      || fm.content.split('\n').find(l => l.trim() && !l.startsWith('#'))?.slice(0, 200)
      || '';
    const html    = renderMarkdown(fm.content);

    return { title, slug, url: `/blog/${slug}`, date, dateFormatted: formatDate(date), excerpt, html, source: fname };
  });

  const bySlug = new Map();
  posts.forEach(p => {
    if (bySlug.has(p.slug)) {
      throw new Error(`blog/${p.source} and blog/${bySlug.get(p.slug)} both use the slug "${p.slug}" — set a different \`slug:\` in one of them.`);
    }
    bySlug.set(p.slug, p.source);
  });

  // Newest first
  posts.sort((a, b) => new Date(b.date) - new Date(a.date));

  writePostPages(blogDir, posts);

  // The homepage only needs enough to list posts; the body lives on each post's page.
  const index = posts.map(({ title, slug, url, date, dateFormatted, excerpt }) =>
    ({ title, slug, url, date, dateFormatted, excerpt }));
  fs.writeFileSync(indexPath, JSON.stringify({ posts: index }, null, 2));
  console.log(`✓ blog-index.json + blog/*.html — ${posts.length} post(s)`);
  posts.forEach(p => console.log(`  ${SITE_URL}${p.url}`));
}

// ── Photos ────────────────────────────────────────────────────────────────────
async function updatePhotos() {
  const cloudName  = process.env.CLOUDINARY_CLOUD_NAME;
  const apiKey     = process.env.CLOUDINARY_API_KEY;
  const apiSecret  = process.env.CLOUDINARY_API_SECRET;
  const folder     = process.env.CLOUDINARY_FOLDER === undefined ? 'photos' : process.env.CLOUDINARY_FOLDER;

  if (!cloudName || !apiKey || !apiSecret) {
    console.error(
      'Missing Cloudinary credentials.\n' +
      'Set CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET\n' +
      'in your environment or in a .env file at the project root.'
    );
    process.exit(1);
  }

  const cloudinary = require('cloudinary').v2;
  cloudinary.config({ cloud_name: cloudName, api_key: apiKey, api_secret: apiSecret });

  console.log(`Fetching photos from Cloudinary folder "${folder}"…`);
  let resources = [];
  let nextCursor;

  do {
    const opts = { type: 'upload', max_results: 500 };
    if (folder) opts.prefix = folder;
    if (nextCursor) opts.next_cursor = nextCursor;
    const res = await cloudinary.api.resources(opts);
    resources = resources.concat(res.resources || []);
    nextCursor = res.next_cursor;
  } while (nextCursor);

  const out = resources.map(r => ({
    public_id:  r.public_id,
    secure_url: r.format === 'heic'
      ? r.secure_url.replace('/upload/', '/upload/f_jpg,q_auto/')
      : r.secure_url,
    photo_date: r.created_at,
  }));

  // Newest first
  out.sort((a, b) => new Date(b.photo_date) - new Date(a.photo_date));

  const outPath = path.join(ROOT, 'photos-data.json');
  fs.writeFileSync(outPath, JSON.stringify({ resources: out }, null, 2));
  console.log(`✓ photos-data.json — ${out.length} photo(s)`);
}

// ── Main ──────────────────────────────────────────────────────────────────────
(async () => {
  const args    = process.argv.slice(2);
  const blogOnly   = args.includes('--blog');
  const photosOnly = args.includes('--photos');
  const both = !blogOnly && !photosOnly;

  try {
    if (both || blogOnly)   await updateBlog();
    if (both || photosOnly) await updatePhotos();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
})();
